In [1]:
import numpy as np

In [4]:
a = [1,2,3]
b = [4,5,6]

In [8]:
try:
    a*b
except Exception as e:
    print(e)

can't multiply sequence by non-int of type 'list'


In [9]:
a_numpy = np.array(a)
b_numpy = np.array(b)
a_numpy * b_numpy

array([ 4, 10, 18])

In [18]:
x = np.array([1,23,4])
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
x.ndim, y.ndim

(1, 2)

In [21]:
x.shape, y.shape

((3,), (3, 3))

In [29]:
r1 = np.array([1,23,4],dtype='int64')
r1.dtype

dtype('int64')

In [32]:
r1.size

3

In [13]:
x = np.arange(3).reshape(1,3,1)
print(x)

[[[0]
  [1]
  [2]]]


In [14]:
x.ndim

3

### accessing elements

In [17]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print(x.ndim)
print(x.shape)

2
(3, 3)


In [21]:
x[2,1]

8

In [25]:
x[1]

array([4, 5, 6])

In [35]:
# 2nd row, column 1st and last not the middle
x[1,0::2]

array([4, 6])

In [37]:
# 2nd column, row 1st and last not the middle
x[0::2,1]

array([2, 8])

### zeros, ones, random

In [17]:
a = np.zeros((1,2,5,3,2))
a

array([[[[[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]]]]])

In [14]:
a.shape

(1, 2, 5, 3)

In [15]:
a.ndim

4

In [16]:
a.size

30

In [22]:
np.random.rand(1,2)

array([[0.66892681, 0.41998975]])

In [33]:
r = np.ones((5,5),dtype='int')
print(r)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [34]:
r[1:4,1:4] = 0
r[2,2] = 9
r

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [1]:
import numpy as np

In [9]:
list_ = [1,2,3,4,5]

x= np.array(list)
print(x)
print(type(x))

[<class 'list'>]
<class 'numpy.ndarray'>


In [19]:
np.random.rand(3,4,5)

array([3, 3, 3, 3, 3])

In [20]:
np.random.random_integers(5)

C:\Users\being\AppData\Local\Temp\ipykernel_11700\339360557.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  np.random.random_integers(5)


1

In [21]:
np.random.random(2)

array([0.85922121, 0.74010808])

#### Numpy random (np.random.______)

In [ ]:
# types          |                    input               |                    output               |
# rand           |shpe of the array                       | random values [0,1) and continuos values
# randn          |shpe of the array                       | Return a sample (or samples) from the “standard normal” distribution.
# randint        |(low, high=None, shape, dtype=int)      | given size ki array and elements are always = input integer and integer values
# random         |nothing or shape                        | generates a random number (if input = None) or an array of given shape
# random_sample  |                                        |

#### Numpy random (np.random.______) 
#### ************ END ******************

#### Mathematical Operations

In [18]:
import numpy as np

In [19]:
np.random.randint(4,6,[3,4])

array([[5, 5, 4, 5],
       [4, 4, 5, 5],
       [4, 4, 4, 5]])

In [9]:
a+b

array([102, 104, 106, 108, 110])